blank_issues_enabled: true
contact_links:
  - name: Ask a question / Discussion
    url: https://github.com/PRABHUSIDDARTH/sidd-ai/discussions
    about: Please use Discussions for general questions instead of an issue.
